package com.example.movie_ticket_sales_website.model;
import jakarta.persistence.*;
import org.springframework.data.annotation.Id;

////Seat status description (available or reserved)
@Entity
@Table(name = "Seat")
public class Seat {
    @jakarta.persistence.Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "seat_id")
    private int id;  // Auto-generated by the database

    @Column(name = "seat_name")
    private String name;

    @Column(name = "row_label")
    private char row;

    @Column(name = "col_number")
    private int column;

    @Column(name = "is_available")
    private boolean isAvailable;

    @Column(name = "cancel_code")
    private String cancelCode;

    public Seat(char row, int column) {
        this.row = row;
        this.column = column;
        this.name = row + String.valueOf(column + 1);
        this.isAvailable = true; // auto available
        this.cancelCode = "null";
    }

    public Seat() {
        this.row = '_';
        this.column = 0;
        this.name = row + String.valueOf(column + 1);
        this.isAvailable = true; // auto available
        this.cancelCode = "null";
    }

    public int getId() { return id; }

    public String getName() { return name; }

    public char getRow() { return row; }

    public int getColumn() { return column; }

    public int getSeatId() {
        return id;
    }

    public void setSeatId(int id) {
        this.id = id;
    }

    public boolean isAvailable() {
        return isAvailable;
    }

    public void reserve() {
        isAvailable = false;
    }

    public void cancel() {
        isAvailable = true;
    }

    public String getCancelCode() {return cancelCode;}

    public void setCancelCode(String cancelCode) {this.cancelCode = cancelCode;}
}
